### ISSUE TITLE
PG0.5 モードの時、変数名の先頭に & が指定できてしまう

### ISSUE THREAD

**Issue by mhgp** [nakkag/pg0_web#1]
# 症状
次の条件の時、変数名には使えないはずの `&` が変数名として使えてしまいます。
 * PG0.5 モード
 * 変数名の先頭が `&`

# サンプルコード
```pg0
#option("pg0.5")
var &foo = 1 // 構文エラーになるはずが &foo 変数が作成されてしまう
```

# 期待する動作
構文エラーが出る。

# 試した環境
 * Firefox 120.0.1 (64 ビット)
 * Google Chrome  119.0.6045.200

ウェブ版のバージョンはわかりませんが、 2023-12-08T21:24(日本時間) 時点で再現します。
なお、ダウンロード版 (ver 0.3.6) では構文エラーになりました。

# 備考
恐らく `script_parse.js` の 110行目 `if (sci.extension) {` を `if (sci.extension && pi.type == SYM_FUNC) {` に変更すればよいのではないかと思います。

**Comment by nakkag** [comment]
ご報告ありがとうございます。

変数名の先頭に&がある場合はエラーにする必要がありますが、関数の引数で参照渡しをする場合は引数宣言の先頭に&を使います。
そのため解析時ではなく実行時にエラーチェックするように修正しました。
